In [1]:
import requests
import time
from bs4 import BeautifulSoup
from six.moves import urllib
import wget
import re

In [84]:
#Collect the pdfs
for i in range(2007,2018):
    break
    time.sleep(1)
    url='http://www.comune.torino.it/statistica/osservatorio/annuario/{}/'.format(i)
    response = requests.get(url)
    soup = BeautifulSoup(response.text, 'html.parser')
    download_url = url+[t['href'] for t in soup.findAll('a') if 'toponomastica' in str(t).lower() and 'pdf' in str(t).lower()][0]
    urllib.request.urlretrieve(download_url,'topo_{}.pdf'.format(i))

In [85]:
from PyPDF2 import PdfFileReader, PdfFileWriter
import numpy as np

In [86]:
# find pages
def  findText(f, slist):
    file = open(f, 'rb')
    pdfDoc = PdfFileReader(file)
    pages = []
    for i in range(pdfDoc.getNumPages()):
        content = pdfDoc.getPage(i).extractText().lower()
        if np.all([s.lower() in content for s in stringList]):
            if i not in pages:
                pages.append(i)
    return pages

#extract pages
def extractPage(f, fOut, pages):
    file = open(f, 'rb')
    output = PdfFileWriter()
    pdfOne = PdfFileReader(file)
    for i in pages:
        output.addPage(pdfOne.getPage(i))
    outputStream = open(fOut, "wb")
    output.write(outputStream)
    outputStream.close()
    return

In [87]:
for year in range(2008,2018):
#for pdfFile in ["topo_2007.pdf"]:
    pdfFile="topo_{}.pdf".format(year)
    print(pdfFile)
    outPdfFile = pdfFile.replace(".pdf","_searched_extracted.pdf")
    stringList = ["tavola", "costruzioni",'circoscrizione']
    extractPage(pdfFile, outPdfFile, findText(pdfFile, stringList))

topo_2008.pdf
topo_2009.pdf

PdfReadWarning: Xref table not zero-indexed. ID numbers for objects will be corrected. [pdf.py:1736]

topo_2010.pdf
topo_2011.pdf
topo_2012.pdf
topo_2013.pdf
topo_2014.pdf
topo_2015.pdf
topo_2016.pdf
topo_2017.pdf

In [76]:
def correct_data(x):
    if not (type(x)==int or type(x)==float):
        return x
    if type(x/1000)==int:
        return x/1000
    else:
        return x

In [88]:
year=2016
pdfFile="topo_{}.pdf".format(year)
print(pdfFile)
outPdfFile = pdfFile.replace(".pdf","_searched_extracted.pdf")
df=read_pdf(outPdfFile)

topo_2016.pdf

In [104]:
#For 2016 at least
df.drop([c for c in df.columns if 'Unnamed' in c],axis=1,inplace=True)

In [102]:
df

,Circoscrizione,1,2,3,4,5,6,7,8,Totale
0,Numero permessi ritirati,4.00,7.000,5.000,8.000,5.000,8.0000,4.000,20.000,61.000
1,Volume Totale mc *,19.05,11.537,10.190,24.778,2.112,1.1254,14.138,22.635,98.549
2,Sup. Coperta mq,256.00,502.000,730.000,1.109,129.000,798.0000,450.000,1.007,4.981
3,Sup. Utile Abitabile,706.00,2.397,2.279,4.190,572.000,2.8880,1.600,3.924,18.556
4,Sup. Servizi/Accessori mq,76.00,2.650,1.348,3.664,138.000,884.0000,3.110,4.069,15.939
5,Sup. Altre Destinaz mq,NaN,NaN,NaN,382.000,NaN,NaN,NaN,NaN,382.000
6,Sup. Tot. Fabbricato,706.00,5.047,3.627,8.282,710.000,3772.0000,4.710,7.708,34.562
7,Num. Tot. Abitaz.,17.00,29.000,28.000,60.000,6.000,43.0000,20.000,48.000,251.000
8,Num. Tot. Stanze,25.00,109.000,93.000,192.000,13.000,88.0000,66.000,143.000,729.000
9,Num. Tot. Acc.,20.00,105.000,47.000,122.000,21.000,57.0000,75.000,133.000,580.000
10,Abitaz. con 1 stanza,13.00,1.000,2.000,1.000,1.000,NaN,1.000,5.000,24.000
11,Abitaz. con 2 stanze,3.00,3.000,5.000,16.000,2.000,13.0000,5.000,13.000,60.000
12,Abitaz con 3 stanze,NaN,3.000,NaN,13.000,NaN,19.0000,5.000,21.000,61.000
13,Abitaz con 4 stanze,NaN,17.000,20.000,30.000,3.000,9.0000,7.000,6.000,92.000
14,Abitaz con 5 stanze,NaN,5.000,1.000,NaN,NaN,2.0000,1.000,3.000,12.000
15,Abitaz con 6 stanze e più,1.00,NaN,NaN,NaN,NaN,NaN,1.000,NaN,2.000
16,Abitaz fino a 45 mq,14.00,2.000,1.000,4.000,NaN,NaN,1.000,6.000,28.000
17,Abitaz da 46 a 75 mq,2.00,13.000,6.000,31.000,3.000,35.0000,6.000,13.000,109.000
18,Abitaz da 76 a 110 mq,NaN,12.000,15.000,23.000,NaN,4.0000,12.000,23.000,89.000
19,Abitaz oltre 110 mq,1.00,2.000,6.000,2.000,3.000,4.0000,1.000,6.000,25.000